name: Debug

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Run with latest stable Deno.

      - run: deno info

      - run: echo $GITHUB_WORKSPACE
