name: Release on tag push

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    env:
      DENO_DIR: /home/runner/.cache/deno
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.1
        with:
          deno-version: "~2.0"

      - name: Use dependency cache
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Run static checks(type check, format, lint)
        run: deno task static-checks

      - name: Run tests
        run: deno task test

      - name: Publish to JSR
        run: deno publish

      - name: Build executables
        run: |
          NON_WIN_ARCHES=(x86_64-unknown-linux-gnu x86_64-apple-darwin aarch64-apple-darwin)
          for ARCH in "${NON_WIN_ARCHES[@]}"; do
            deno compile --target $ARCH -o nosdump -A mod.ts
            zip -r "nosdump-${ARCH}" nosdump
          done

          WIN_ARCHES=(x86_64-pc-windows-msvc)
          for ARCH in "${WIN_ARCHES[@]}"; do
            deno compile --target $ARCH -o nosdump.exe -A mod.ts
            zip -r "nosdump-${ARCH}" nosdump.exe
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: nosdump-*.zip
